[project]
name = "telegram-youtube-bot"
version = "0.1.0"
description = "Telegram bot that converts YouTube videos to MP3"
requires-python = ">=3.11"
dependencies = [
    "ffmpeg-python>=0.2.0",
    "python-telegram-bot[all]==20.8",
    "telegram>=0.0.1",
    "yt-dlp>=2024.12.13",
]

[tool.uv]
package = false
